trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      **/TournamentManager.Client.csproj
      **/TournamentManager.Server.csproj
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      **/TournamentManager.Client.csproj
      **/TournamentManager.Server.csproj
    arguments: '--configuration Release --framework net7.0 --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'